// Regular Stack / Shadow Stack
#define MSR_IA32_PL3_SSP			0x000006A7U
#define MAX_STACK_FRAMES 512
#define RTL_WALK_KERNEL_MODE_STACK		0x00000000
#define RTL_WALK_USER_MODE_STACK 0x00000001

// E/KPROCESS
#define EPROCESS_ACTIVEPROCESSLINK_OFFSET 0x448
#define EPROCESS_SE_AUDIT_PROCESS_CREATION_INFO_OFFSET 0x5c0
#define EPROCESS_SE_AUDIT_PROCESS_CREATION_INFO_IMAGE_FILE_NAME_OFFSET 0x0
#define EPROCESS_VAD_ROOT_OFFSET 0x7d8
#define EPROCESS_MITIGATION_FLAGS2_VALUES_OFFSET 0x9d4
#define EPROCESS_ACTIVE_PROCESS_LINKS 0x448
#define EPROCESS_THREAD_LIST_HEAD 0x5e0
#define EPROCESS_FLAGS3 0x87c

// E/KTHREAD
#define KTHREAD_HEADER_OFFSET 0x000
#define ETHREAD_THREADLISTENTRY_OFFSET 0x4e8
#define KTHREAD_TRAPFRAME_OFFSET 0x090

// VAD
#define VAD_MAX_ENTRIES 256
#define VAD_PROTECTION_OFFSET 0x30
#define VAD_SUBSECTION_OFFSET 0x048
#define VAD_CONTROL_AREA_OFFSET 0x0
#define VAD_SEGMENT_OFFSET 0x0
#define VAD_FILE_POINTER_OFFSET 0x40
#define VAD_ENTRY_POINT_OFFSET 0x48
#define VAD_MITIGATION_FLAGS2_VALUES_OFFSET 0x9d4

// VM
#define PROCESS_VM_READ 0x0010

#define MM_ZERO_ACCESS         0x0  
#define MM_READONLY            0x1  
#define MM_EXECUTE             0x2  
#define MM_EXECUTE_READ        0x3  
#define MM_READWRITE           0x4  
#define MM_WRITECOPY           0x5  
#define MM_EXECUTE_READWRITE   0x6  
#define MM_EXECUTE_WRITECOPY   0x7  
#define MM_NOACCESS            0x8  
#define MM_GUARD_PAGE          0x9 
#define MM_NOCACHE             0xA 
#define MM_WRITECOMBINE        0xB 
#define MM_EXECUTE_NOCACHE     0xC  
#define MM_EXECUTE_WRITECOMBINE 0xD 
#define MM_EXECUTE_GUARD_PAGE  0xE 
#define MM_EXECUTE_NOACCESS    0xF 

// Others
#define PROCESS_TERMINATE 0x0001 
